const Constants = {
  SORT_ASC: "ASC",
  SORT_DESC: "DESC",
  FILTER_YEAR: "FILTER_YEAR",
  GET_UNIQUE_YEARS: "GET_UNIQUE_YEARS",
  POPULATE_DROPDOWN: "POPULATE_DROPDOWN",
  FETCH_DATA: "FETCH_DATA",
};
export default Constants;
