const Constants = {
  SORT_ASC: "ASC",
  SORT_DESC: "DESC",
  FILTER_YEAR: "FILTER_YEAR",
  GET_UNIQUE_YEARS: "GET_UNIQUE_YEARS",
  FETCH_DATA: "FETCH_DATA",
  LAUNCH_API: "LAUNCHES",
  MISSIONS_API: "MISSIONS",
  LOADING: "LOADING"
};

export default Constants